# Config file for automatic testing at travis-ci.org

language: python

addons:
  postgresql: "9.3"

python:
  - "3.4"
  - "3.3"
  - "2.7"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
before_script:
  - psql -d template1 -c 'create extension hstore;' -U postgres
  - psql -c 'create database psqltest;' -U postgres
script: cd psqltest;python manage.py test
